controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: velocity_controllers/DiffDriveController

diff_drive_controller:
  ros__parameters:
    use_stamped_vel: false
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    wheel_separation: 0.28        # senin modeline göre ayarla
    wheel_radius: 0.04            # senin modeline göre ayarla
    publish_limited_velocity: true
    velocity_rolling_window_size: 10
